Copy over new version of Milo's geo-based locales
adobecom/bacom pull request #130
Opened 2023-07-13 23:15 UTC by hparra

See https://github.com/adobecom/milo/pull/915 and https://github.com/adobecom/milo/pull/938

**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/?martech=off
- After: https://hparra-patch-2--bacom--hparra.hlx.page/?martech=off

2023-07-13 23:57 UTC, JasonHowellSlavin approved these changes
LGTM. Alphabetizing for the win!

2023-07-14 21:12 UTC, meganthecoder approved these changes

2023-07-14 21:16 UTC, meganthecoder commented
@hparra There's no ui or functionality to verify here, right? It's just adding the new `lang` and `reg` properties and alphabetizing?

2023-07-14 21:45 UTC, hparra commented
@meganthecoder There is new functionality in Milo that is enabled when these values exist. You can confirm in test urls that HTML lang attribute now only uses language subtag instead of full tag, e.g `<html lang="en">` vs. `<html lang="en-US">`. See https://github.com/adobecom/milo/pull/915 and linked issue for more details. Milo features use `getConfig().locale` and do not read locale from this attribute.

2023-07-14 22:18 UTC, meganthecoder commented
@hparra Cool, I updated the description to reflect that and assigned myself to verify. Is the `reg` tag being used yet? I didn't see anything in the PRs you mentioned.

2023-07-14 22:22 UTC, hparra commented
> Is the `reg` tag being used yet?

Not yet. A couple of new features use it and I will begin porting existing features to use it one by one -- those changes will be in Milo only but it will affect all Milo consumers. There will be additional comms of those.

2023-07-14 23:04 UTC, meganthecoder requested changes
There are a few locales added that we don't support in bacom. Also, when I was testing, I saw that CaaS cards weren't loading for `la`

2023-07-14 23:04 UTC, meganthecoder commented on scripts/scripts.js
> +    ec: { ietf: 'es-419', lang: 'es', reg: 'EC', tk: 'oln4yqj.css' },
Same for ec (ecuador)
```suggestion
```

2023-07-14 23:04 UTC, meganthecoder commented on scripts/scripts.js
> +    gt: { ietf: 'es-419', lang: 'es', reg: 'GT', tk: 'oln4yqj.css' },
Same for gt (guatemala)
```suggestion
```

2023-07-14 23:04 UTC, meganthecoder commented on scripts/scripts.js
> +    pr: { ietf: 'es-419', lang: 'es', reg: 'PR', tk: 'oln4yqj.css' },
Same for pr (puerto rico)
```suggestion
```

2023-07-14 23:13 UTC, hparra commented
> There are a few locales added that we don't support in bacom

This should be OK. `locales` is just a source of truth for mappings. `locales` should NOT be used to enable or disable a particular locale. I can remove but it makes syncing more difficult.

> Also, when I was testing, I saw that CaaS cards weren't loading for `la`

This is probably not OK and is the sort of thing I was afraid of. Can we sync on this so I can understand what is happening?

2023-07-17 21:39 UTC, hparra commented
Waiting for https://github.com/adobecom/milo/pull/945

2023-07-24 14:31 UTC, JasonHowellSlavin commented
@hparra @meganthecoder looks like `la` cards are loading again on this one, some links: 
https://hparra-patch-2--bacom--adobecom.hlx.page/la/customer-success-stories?martech=off
https://hparra-patch-2--bacom--adobecom.hlx.page/la/resources/main

2023-07-24 21:50 UTC, meganthecoder commented
I believe a different solution was determined here: https://github.com/adobecom/milo/pull/963

@hparra Can this PR be closed?

2023-07-24 22:01 UTC, hparra commented
@meganthecoder I was waiting until handoff to close all PRs but I think we're ok.

2023-07-24 22:01 UTC, closed without merging